services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-contextionary'
      ENABLE_MODULES: 'text2vec-contextionary'
      CONTEXTIONARY_URL: contextionary:9999
      QUERY_DEFAULTS_LIMIT: 25
      CLUSTER_HOSTNAME: 'node1'
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
  app:
    build:
      context: .
    depends_on:
      weaviate:
        condition: service_healthy
    command: python main.py
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${FRIENDLI_TOKEN}
    stdin_open: true
    tty: true
  data-loader:
    profiles: ["tools"]
    build:
      context: .
    depends_on:
      weaviate:
        condition: service_healthy
    command: bash -c "python scripts/generate_profiles.py && python scripts/load_data.py"
